version: '3.8'

services:
  # Development Backend with hot reload
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: laptop-store-backend-dev
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
      - DATABASE_URL=laptop_store.db
      - RELOAD=true
    volumes:
      # Mount source code for hot reload
      - ./backend:/app
      - backend_dev_data:/app/data
    networks:
      - laptop-store-network

  # Development Frontend with hot reload
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: laptop-store-frontend-dev
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_BASE_URL=http://localhost:8000
      - CHOKIDAR_USEPOLLING=true
    volumes:
      # Mount source code for hot reload
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - laptop-store-network

volumes:
  backend_dev_data:
    driver: local

networks:
  laptop-store-network:
    driver: bridge
